### ISSUE TITLE
Would you like to put your code under some license?

### ISSUE THREAD

**Issue by RSusmita** [akira108/MinimumOpenCVLiveCamera#1]
Hi Akira ,

I want to use this code for my application , would you like to put your code under some license.

Thanks & Regards,
Susmita

**Comment by akira108** [comment]
Hi!

Thank you for using that in your app. I'll go with MIT License.

Akira

iPhoneから送信

2017/08/24 15:31、RSusmita <notifications@github.com> のメッセージ:

**Comment by RSusmita** [comment]
Hi Akira,

Thanks for the quick reply . Can you put the license in Github repository.

Thanks & Regards,
Susmita

**Comment by akira108** [comment]
Sorry for super super late reply. added.
